In [1]:
# To support both python 2 and python 3
from __future__ import division, print_function, unicode_literals

# Common imports
import numpy as np
import os
import pandas as pd

# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt
plt.rcParams['axes.labelsize'] = 14
plt.rcParams['xtick.labelsize'] = 12
plt.rcParams['ytick.labelsize'] = 12

# Where to save the figures
PROJECT_ROOT_DIR = "."
CHAPTER_ID = ""
IMAGES_PATH = os.path.join(PROJECT_ROOT_DIR, "images", CHAPTER_ID)

def save_fig(fig_id, tight_layout=True, fig_extension="png", resolution=300):
    path = os.path.join(IMAGES_PATH, fig_id + "." + fig_extension)
    print("Saving figure", fig_id)
    if tight_layout:
        plt.tight_layout()
    plt.savefig(path, format=fig_extension, dpi=resolution)

In [2]:
result = pd.read_csv('./data/birch_recommend/birch6_itemCF_cosine.csv')
result = result.set_index('Unnamed: 0')

In [4]:
result[result.cluster==2]

            cluster  topN  precision  recall  f1score
Unnamed: 0
12                2     5        0.0     0.0      0.0
13                2    10        0.0     0.0      0.0
14                2    15        0.0     0.0      0.0
15                2    20        0.0     0.0      0.0
16                2    25        0.0     0.0      0.0
17                2    30        0.0     0.0      0.0

In [80]:
summary = pd.DataFrame(columns=result.columns)
for i in range(5,35,5):
    summary = summary.append(result[result.topN==i].describe().iloc[1])
summary.drop(columns=['cluster'])

      topN  precision    recall   f1score
mean   5.0   0.152943  0.063670  0.089484
mean  10.0   0.163546  0.134323  0.146685
mean  15.0   0.166064  0.200873  0.180787
mean  20.0   0.162532  0.255328  0.197634
mean  25.0   0.159508  0.301651  0.207815
mean  30.0   0.156086  0.339380  0.213137